### PR TITLE
CLI unit testing setup powered by vitest.

### PR DESCRIPTION
**Pull request by anicolao**
Usage:

npm run test

Also required by precommit.

### CODE REVIEW

**Comment by Tsangares** [comment]
What is the justification for this unit test? 

And the justification for implementing a testing system? Does it require a new dependency?

**Comment by anicolao** [comment]
This specific unit test is just a simple example of how to write a test so that the unit testing framework itself can be easily understood and documented.

All dependencies are listed in `package.json` so the diffs on that file are authoritative. This change contains only development dependencies so I would say it contains "no dependencies" in that if you can write code in this npm driven system at all, you can use the new tools that this introduces. But from another point of view it introduces dependencies on chai types, vitest, and chrome's code coverage (c8).

We had a long thread on discord about testing the caching change and so it's a bit odd to me that you're asking why there's a new unit test system; you seem really worried about that code being buggy and having a simple unit test ought to put that fear to rest. Personally I think that particular change was so simple and obviously correct I would have shipped it days ago, but then I wrote it so :shrug:

In any event, the unit testing system will be something I use extensively to cover my code past and future, so that we can easily change the battle calculator or any other parts of the code people feel are mysterious without fear that we've broken the system.

**Comment by Tsangares** [comment]
> We had a long thread on discord about testing the caching change and so it's a bit odd to me that you're asking why there's a new unit test system; you seem really worried about that code being buggy and having a simple unit test ought to put that fear to rest. Personally I think that particular change was so simple and obviously correct I would have shipped it days ago, but then I wrote it so shrug

I feel antagonized by these words. A purpose of Pull Requests are to document changes and I wanted more text here elaborating this change. The questions I asked would provide sufficient details. 

You wrote a sufficient test for the caching system. My confidence is set aside when I am testing something and using it for a few days, to me, is an important component of a robust test. Not all code needs a robust test but the cache did. There is no urgency to generate new plugin releases.

The dependencies you added are:
```
    "@types/chai": "^4.3.3",
    "c8": "^7.12.0",
    "chai": "^4.3.6",
    "vitest": "^0.19.1",
```

Tests for the battle calc are a great idea to provide the confidence we need and expect in those calculations, I appreciate it!

**Comment by anicolao** [comment]
> > We had a long thread on discord about testing the caching change and so it's a bit odd to me that you're asking why there's a new unit test system; you seem really worried about that code being buggy and having a simple unit test ought to put that fear to rest. Personally I think that particular change was so simple and obviously correct I would have shipped it days ago, but then I wrote it so shrug
> 
> I feel antagonized by these words. A purpose of Pull Requests are to document changes and I wanted more text here elaborating this change. The questions I asked would provide sufficient details.

I am sorry! I didn't mean to antagonize you. I guess the reverse is also true: I felt antagonized by the question because I thought we'd agreed a unit test scheme was needed and so I added it, only to be questioned on its dependencies and value.

It'd be a good idea to add something about documenting the intent of changes to the WORKFLOW.md documentation so that everyone knows where this kind of documentation goes. As that draft currently stands, no place is currently identified for us to create a record of these discussions/decisions.

I would prefer if we document changes inside the git changelog descriptions. Pull requests are an artifact of github workflow that won't stay with the source code if we switch to a different git hosting provider and I don't want to lose the historical record if someday we had a need to switch.

**Comment by Tsangares** [comment]
I am sorry for antagonizing you. Asking questions in a pull request appeared like an exceedingly normal thing to do; I will make a template for a PRs to make my general questions more clear and so I don't have to bother people when I ask them.

**Comment by Tsangares** [comment]
Our current collaboration tool is github so I feel it is still an appropriate place for notes on incentives.

**Review by Tsangares — APPROVED** [review]

**Pull request merged**
