### PR TITLE
Fix up git section to point at DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by anicolao**

### CODE REVIEW

**Review by Tsangares — CHANGES_REQUESTED** [review]
There is a user (tester), that wants the git version, the latest version, but does not want to contribute. 

They don't need webpack & their use case is not documented in DEVELOPMENT.md

I think this section should be revised not removed & the link to development should stay & is for anyone who wants to go beyond testing and develop.

**Comment by anicolao** [comment]
There’s no way to get the latest version without someone building it. We coudl make a different git repository that contains builds of anything merged to main, and have github actions populate it. Seems like a lot of work, but it can be done.

**Comment by Tsangares** [comment]
We can store the latest build in the repo? We can also offered it packed.

**Comment by anicolao** [comment]
I don’t see the advantage of build artifacts being mixed into the source code repo rather than in their own repo? If there is an advantage, then by all means. But we’re talking about potentially needing to store an android app, an ios app, the chrome extension, and the safari userscript build? If we’re going to do something like that I rather favour separate repos for each build that we support off of tip of tree. 

Again to me this seems like a lot of work to save someone having to type one or two commands following DEVELOMENT.md.

**Comment by Tsangares** [comment]
We don't need to support the artifacts for ios, android, linux, mac and windows. We may only do the files for chrome as a zip. Testing it in chrome will be a comparable but not replacement of a test for ios, android, linux, mac and windows.

**Comment by Tsangares** [comment]
In their own repo seems the way to go though

**Comment by anicolao** [comment]
Closing this pull request as some new solution is needed to support testers pulling ready to go builds from github.

**Pull request closed without merging**
