### PR TITLE
Remove NPA functionality so that the extensions can co-exist

### PR DESCRIPTION
**Pull request by anicolao**

### CODE REVIEW

**Comment by anicolao** [comment]
I have tested this build with NPA 1.18 and the two appear totally compatible. I have pushed NPA 1.18 to the Chrome Store and expect it to roll out to NPA's users in about 48h. 

With NPA 1.16 things are almost good, but the "Intel" button and the "Research" button overlap. "Research" is still easy to read and click, but "Intel" is mostly obscured so you'd really have to know what it was to use it. Not tragic, but will be nice to have 1.18 live so that they are 100% compatible.

**Comment by anicolao** [comment]
[1.18 is finally live](https://chrome.google.com/webstore/detail/neptunes-pride-agent/gpcdekpemhpdcacfnafnflnlakelfefh) in the Chrome Web Store so anyone can test the interop.

**Comment by Tsangares** [comment]
Hey @anicolao, 

I am really not trying to be inflammatory. I am just over-committed to things. I changed the name of the NPA agent's main function & haven't pushed it to GitHub yet. So both the plugins with work together & there might be some issues if you included equivalent functions names as mine because I define all of mine as constant.

Please, just be patient with me. I will have to slowly remove your content & things. I apologize for my lack of time commitment.

Do whatever you need to do; tell people you need to uninstall SAT if they need to its okay. I am just here building utilities like you are and I will continue to do so here. Continue at your own pace in whatever way you find is reasonable.

I hope you are doing well & I apologize that I didn't have the bandwidth to do face-to-face video calls to help communicate our intentions. I felt like we probably could have cooperated better but I just don't have the bandwidth & am particularly over-committed to be able to manager/cooperate with someone of your great programming capabilities.

**Comment by anicolao** [comment]
Accepting this pull request would have been the easiest way to ensure users could use both extensions immediately.

Compatibility isn't just about function names, it's about how many features overlap - API key merging, HUD display, message text processing - these overlapping features are unlikely to work well together when both extensions are installed. Making the extensions have no overlap so that users could have a clear path to getting everything seems like a better solution to me than implementing everything twice, which is what we seem to be doing now.

As you can see I am publishing detailed changelogs and the project continues to be open source; you can choose to be compatible or not as you wish.

**Pull request closed without merging**
